import type { GuidedTour } from './entities/guided-tour.entity';
import type { UpdateGuidedTourDto } from './dto/update-guided-tour.dto';
import { ForbiddenException } from '@nestjs/common';
import { TourEnvironment, TourSandboxStatus } from './entities/guided-tour.entity';

export type TourLabEligibility = Pick<GuidedTour, 'targetUrl' | 'triggerConditions' | 'environment' | 'sandboxStatus'>;

export const SDK_LAB_TARGET_PATH_SEGMENT = '/dashboard/sdk-tests/';

/** Champs interdits aux développeurs sur un parcours lab (whitelist stricte). */
export const DEVELOPER_LAB_FORBIDDEN_UPDATE_FIELDS = [
  'targetUrl',
  'isActive',
  'priority',
  'triggerConditions',
  'simulationContext',
  'replayPolicy',
  'replayAfterDays',
] as const satisfies ReadonlyArray<keyof UpdateGuidedTourDto>;

const FORBIDDEN_FIELD_LABELS: Record<(typeof DEVELOPER_LAB_FORBIDDEN_UPDATE_FIELDS)[number], string> = {
  targetUrl: 'URL cible (targetUrl)',
  isActive: 'statut actif (isActive)',
  priority: 'priorité (priority)',
  triggerConditions: 'conditions de déclenchement (triggerConditions)',
  simulationContext: 'contexte de simulation (simulationContext)',
  replayPolicy: 'politique de replay (replayPolicy)',
  replayAfterDays: 'délai de replay (replayAfterDays)',
};

/** Parcours publiés via le moteur contextuel (lab SDK, app de test, etc.). */
export function isContextualAutogeneratedTour(tour: TourLabEligibility): boolean {
  const triggerConditions = tour.triggerConditions;
  if (!triggerConditions || typeof triggerConditions !== 'object') {
    return false;
  }

  if (triggerConditions.source === 'contextual-engine') {
    return true;
  }

  const engine = triggerConditions.contextualEngine;
  return Boolean(engine && typeof engine === 'object');
}

/** Parcours publiés depuis le lab SDK (`/dashboard/sdk-tests/*` + moteur contextuel). */
export function isSdkLabPublishedTour(tour: TourLabEligibility): boolean {
  const targetUrl = normalizeTourPath(tour.targetUrl);
  if (!targetUrl.includes(SDK_LAB_TARGET_PATH_SEGMENT)) {
    return false;
  }

  return isContextualAutogeneratedTour(tour);
}

export function getContextualPublishedByRole(tour: TourLabEligibility): string | undefined {
  const engine = tour.triggerConditions?.contextualEngine;
  if (!engine || typeof engine !== 'object') {
    return undefined;
  }
  const role = (engine as { publishedByRole?: unknown }).publishedByRole;
  return typeof role === 'string' ? role : undefined;
}

/**
 * Parcours autogénérés réservés aux tests développeur (jamais exposés au runtime production).
 * Couvre le sandbox courant et l'historique production non approuvé.
 */
export function isDeveloperOnlyAutogenTour(
  tour: TourLabEligibility & Pick<GuidedTour, 'environment' | 'sandboxStatus'>,
): boolean {
  if (!isContextualAutogeneratedTour(tour)) {
    return false;
  }
  if (tour.environment === TourEnvironment.SANDBOX) {
    return false;
  }
  if (tour.sandboxStatus === TourSandboxStatus.APPROVED) {
    return false;
  }
  if (getContextualPublishedByRole(tour) === 'ADMIN') {
    return false;
  }
  return true;
}

export function isDeveloperOwnedTestTour(
  tour: Pick<GuidedTour, 'createdBy' | 'environment' | 'sandboxStatus' | 'targetUrl' | 'triggerConditions'>,
  userId?: string,
): boolean {
  if (!userId || tour.createdBy !== userId) {
    return false;
  }
  return tour.environment === TourEnvironment.SANDBOX || isDeveloperOnlyAutogenTour(tour);
}

export function normalizeTourPath(url?: string): string {
  return (url ?? '').toLowerCase().split('?')[0];
}

export function isSdkLabTargetPath(url?: string): boolean {
  return normalizeTourPath(url).includes(SDK_LAB_TARGET_PATH_SEGMENT);
}

/**
 * Clé de dédup org pour les parcours sandbox autogénérés (même signature logique = une instance).
 * Le republish transfère la propriété au publisher courant (« qui publie prend »).
 */
export function buildContextualSandboxPublishDedupeKey(
  targetUrl: string,
  intent: string,
  flowSignature: string,
): string {
  return `${normalizeTourPath(targetUrl)}::${intent}::${flowSignature}`;
}

export function isSdkLabPublishScopedByCreator(targetUrl?: string): boolean {
  return isSdkLabTargetPath(targetUrl);
}

export function buildSdkLabPublishDedupeKey(
  publisherId: string,
  targetUrl: string,
  intent: string,
  flowSignature: string,
): string {
  return `${publisherId}::${normalizeTourPath(targetUrl)}::${intent}::${flowSignature}`;
}

/** Lab SDK : une instance par créateur ; sandbox prod : une instance par org. */
export function buildContextualPublishDedupeKey(
  targetUrl: string,
  intent: string,
  flowSignature: string,
  publisherId?: string,
): string {
  if (isSdkLabPublishScopedByCreator(targetUrl) && publisherId) {
    return buildSdkLabPublishDedupeKey(publisherId, targetUrl, intent, flowSignature);
  }
  return buildContextualSandboxPublishDedupeKey(targetUrl, intent, flowSignature);
}

export function isSdkLabTourOwnedBy(
  tour: TourLabEligibility & Pick<GuidedTour, 'createdBy'>,
  userId?: string,
): boolean {
  if (!userId || !isSdkLabPublishedTour(tour)) {
    return false;
  }
  return tour.createdBy === userId;
}

/** Template de test SDK : hors workflow parcours réel (édition, prod, partage, modération). */
export function isSdkLabTemplateTour(tour: TourLabEligibility): boolean {
  return isSdkLabPublishedTour(tour);
}

export function assertSdkLabTemplateWorkflowBlocked(tour: TourLabEligibility): void {
  if (isSdkLabTemplateTour(tour)) {
    throw new ForbiddenException(
      'Les parcours générés par le lab SDK sont des templates de test : édition, promotion, partage et modération sont désactivés.',
    );
  }
}

/**
 * Whitelist développeur : name, description, steps (sans stepTargetUrl hors lab).
 * Rejette toute tentative de modification des champs de portée runtime / identité.
 */
export function assertDeveloperLabTourUpdateAllowed(updateTourDto: UpdateGuidedTourDto): void {
  for (const field of DEVELOPER_LAB_FORBIDDEN_UPDATE_FIELDS) {
    if (updateTourDto[field] !== undefined) {
      throw new ForbiddenException(
        `Les développeurs ne peuvent pas modifier ${FORBIDDEN_FIELD_LABELS[field]} sur un parcours publié depuis le lab SDK.`,
      );
    }
  }

  if (!updateTourDto.steps?.length) {
    return;
  }

  for (const [index, step] of updateTourDto.steps.entries()) {
    const stepTargetUrl = step.stepTargetUrl?.trim();
    if (stepTargetUrl && !isSdkLabTargetPath(stepTargetUrl)) {
      throw new ForbiddenException(
        `Les développeurs ne peuvent pas définir stepTargetUrl hors du lab SDK (étape ${index + 1}).`,
      );
    }
  }
}
