import { ForbiddenException } from '@nestjs/common';
import {
  assertDeveloperLabTourUpdateAllowed,
  buildContextualPublishDedupeKey,
  buildContextualSandboxPublishDedupeKey,
  buildSdkLabPublishDedupeKey,
  isContextualAutogeneratedTour,
  isDeveloperOnlyAutogenTour,
  isSdkLabPublishScopedByCreator,
  isSdkLabPublishedTour,
  isSdkLabTargetPath,
  isSdkLabTemplateTour,
  isLikelyManualContextualTourDerivative,
  isSdkLabTourOwnedBy,
  participatesInContextualPublishDedupe,
} from './guided-tour-lab.util';
import { TourEnvironment, TourSandboxStatus } from './entities/guided-tour.entity';

describe('isContextualAutogeneratedTour', () => {
  it('returns true for contextual-engine metadata on any path', () => {
    expect(
      isContextualAutogeneratedTour({
        targetUrl: '/app/home',
        triggerConditions: { source: 'contextual-engine' },
      }),
    ).toBe(true);
  });
});

describe('isDeveloperOnlyAutogenTour', () => {
  it('returns true for legacy developer autogen in production', () => {
    expect(
      isDeveloperOnlyAutogenTour({
        targetUrl: '/app/home',
        environment: TourEnvironment.PRODUCTION,
        sandboxStatus: null,
        triggerConditions: {
          source: 'contextual-engine',
          contextualEngine: { publishedByRole: 'DEVELOPER' },
        },
      }),
    ).toBe(true);
  });

  it('returns false for admin-published contextual tours', () => {
    expect(
      isDeveloperOnlyAutogenTour({
        targetUrl: '/app/home',
        environment: TourEnvironment.PRODUCTION,
        sandboxStatus: null,
        triggerConditions: {
          source: 'contextual-engine',
          contextualEngine: { publishedByRole: 'ADMIN' },
        },
      }),
    ).toBe(false);
  });

  it('returns false for approved sandbox promotions', () => {
    expect(
      isDeveloperOnlyAutogenTour({
        targetUrl: '/app/home',
        environment: TourEnvironment.PRODUCTION,
        sandboxStatus: TourSandboxStatus.APPROVED,
        triggerConditions: { source: 'contextual-engine' },
      }),
    ).toBe(false);
  });
});

describe('isSdkLabPublishedTour', () => {
  it('returns true for contextual engine tours on sdk-tests paths', () => {
    expect(
      isSdkLabPublishedTour({
        targetUrl: '/dashboard/sdk-tests/simple',
        triggerConditions: {
          source: 'contextual-engine',
          contextualEngine: { scenario: 'simple', flowSignature: 'sig-1' },
        },
      }),
    ).toBe(true);
  });

  it('returns false for manual tours outside sdk-tests', () => {
    expect(
      isSdkLabPublishedTour({
        targetUrl: '/dashboard/transfers',
        triggerConditions: { minTimeOnPage: 30 },
      }),
    ).toBe(false);
  });

  it('returns false for sdk-tests URL without contextual metadata', () => {
    expect(
      isSdkLabPublishedTour({
        targetUrl: '/dashboard/sdk-tests/simple',
        triggerConditions: {},
      }),
    ).toBe(false);
  });
});

describe('contextual publish dedupe participation', () => {
  const canonicalTour = {
    name: 'Parcours SDK',
    triggerConditions: {
      source: 'contextual-engine',
      contextualEngine: {
        source: 'contextual-engine',
        canonicalPublishInstance: true,
        intent: 'primary-action',
        flowSignature: 'sig-1',
      },
    },
  };

  it('includes canonical SDK publish instances', () => {
    expect(participatesInContextualPublishDedupe(canonicalTour)).toBe(true);
  });

  it('excludes dashboard concat derivatives', () => {
    expect(
      participatesInContextualPublishDedupe({
        name: 'Concat - A + B',
        triggerConditions: {
          source: 'contextual-engine',
          contextualEngine: {
            source: 'dashboard-concat',
            intent: 'primary-action',
            flowSignature: 'sig-1',
          },
        },
      }),
    ).toBe(false);
  });

  it('excludes duplicate copies by name and fork metadata', () => {
    expect(
      participatesInContextualPublishDedupe({
        name: 'Parcours d action (copie)',
        triggerConditions: {
          source: 'contextual-engine',
          contextualEngine: {
            intent: 'primary-action',
            flowSignature: 'sig-1',
          },
        },
      }),
    ).toBe(false);
    expect(
      isLikelyManualContextualTourDerivative({
        name: 'Parcours SDK',
        triggerConditions: {
          source: 'contextual-engine',
          contextualEngine: {
            source: 'dashboard-fork',
            forkedFromTourIds: ['tour-a'],
            intent: 'primary-action',
            flowSignature: 'sig-1',
          },
        },
      }),
    ).toBe(true);
  });
});

describe('contextual sandbox publish dedupe', () => {
  it('builds org-wide contextual sandbox dedupe keys', () => {
    expect(
      buildContextualSandboxPublishDedupeKey('/', 'primary-action', 'sig-chili'),
    ).toBe('/::primary-action::sig-chili');
  });

});

describe('sdk lab publish isolation', () => {
  it('scopes dedupe to sdk-tests paths', () => {
    expect(isSdkLabPublishScopedByCreator('/dashboard/sdk-tests/simple')).toBe(true);
    expect(isSdkLabPublishScopedByCreator('/dashboard/users')).toBe(false);
  });

  it('builds publisher-scoped dedupe keys', () => {
    expect(
      buildSdkLabPublishDedupeKey('user-a', '/dashboard/sdk-tests/simple', 'discovery', 'sig-1'),
    ).toBe('user-a::/dashboard/sdk-tests/simple::discovery::sig-1');
  });

  it('uses publisher scope only on sdk lab paths', () => {
    expect(
      buildContextualPublishDedupeKey(
        '/dashboard/sdk-tests/simple',
        'discovery',
        'sig-1',
        'user-a',
      ),
    ).toBe('user-a::/dashboard/sdk-tests/simple::discovery::sig-1');
    expect(
      buildContextualPublishDedupeKey('/', 'primary-action', 'sig-1', 'user-a'),
    ).toBe('/::primary-action::sig-1');
  });

  it('detects lab tour ownership', () => {
    const tour = {
      createdBy: 'user-a',
      targetUrl: '/dashboard/sdk-tests/simple',
      triggerConditions: {
        source: 'contextual-engine',
        contextualEngine: { flowSignature: 'sig-1' },
      },
    };
    expect(isSdkLabTourOwnedBy(tour, 'user-a')).toBe(true);
    expect(isSdkLabTourOwnedBy(tour, 'user-b')).toBe(false);
  });
});

describe('isSdkLabTemplateTour', () => {
  it('matches sdk lab published tours', () => {
    expect(
      isSdkLabTemplateTour({
        targetUrl: '/dashboard/sdk-tests/simple',
        environment: TourEnvironment.SANDBOX,
        sandboxStatus: null,
        triggerConditions: { source: 'contextual-engine' },
      }),
    ).toBe(true);
  });
});

describe('isSdkLabTargetPath', () => {
  it('accepts lab paths', () => {
    expect(isSdkLabTargetPath('/dashboard/sdk-tests/medium')).toBe(true);
  });

  it('rejects production paths', () => {
    expect(isSdkLabTargetPath('/dashboard/users')).toBe(false);
  });
});

describe('assertDeveloperLabTourUpdateAllowed', () => {
  it('allows name, description and lab steps', () => {
    expect(() =>
      assertDeveloperLabTourUpdateAllowed({
        name: 'Renamed',
        description: 'Updated',
        steps: [
          {
            title: 'Step',
            content: 'Content',
            targetSelector: '#cta',
            stepTargetUrl: '/dashboard/sdk-tests/simple',
          },
        ],
      }),
    ).not.toThrow();
  });

  it('rejects forbidden tour fields', () => {
    expect(() => assertDeveloperLabTourUpdateAllowed({ targetUrl: '/dashboard/users' })).toThrow(
      ForbiddenException,
    );
    expect(() => assertDeveloperLabTourUpdateAllowed({ isActive: true })).toThrow(ForbiddenException);
    expect(() => assertDeveloperLabTourUpdateAllowed({ priority: 99 })).toThrow(ForbiddenException);
    expect(() =>
      assertDeveloperLabTourUpdateAllowed({ triggerConditions: { source: 'hijack' } }),
    ).toThrow(ForbiddenException);
    expect(() =>
      assertDeveloperLabTourUpdateAllowed({ simulationContext: { pathname: '/evil' } }),
    ).toThrow(ForbiddenException);
    expect(() => assertDeveloperLabTourUpdateAllowed({ replayPolicy: 'always_on_new_version' as never })).toThrow(
      ForbiddenException,
    );
    expect(() => assertDeveloperLabTourUpdateAllowed({ replayAfterDays: 7 })).toThrow(ForbiddenException);
  });

  it('rejects stepTargetUrl outside lab', () => {
    expect(() =>
      assertDeveloperLabTourUpdateAllowed({
        steps: [{ title: 'S', content: 'C', stepTargetUrl: '/dashboard/billing' }],
      }),
    ).toThrow(ForbiddenException);
  });
});
