import { ForbiddenException } from '@nestjs/common';
import { UserRole } from '../user/entities/user.entity';
import type { GuidedTour } from './entities/guided-tour.entity';
import {
  getContextualPublishedByRole,
  isContextualAutogeneratedTour,
} from './guided-tour-lab.util';
import {
  isAdminActor,
  isDeveloperActor,
  isSdkTokenActor,
  type TourPermissionActor,
} from './guided-tour-permissions.util';
import { TourEnvironment, TourSandboxStatus } from './entities/guided-tour.entity';
import {
  assertCanModerateWhenNotCollaborating,
  assertCanViewTourWithGrants,
  canActorViewTourWithGrants,
  type TourWithAccessGrants,
} from './guided-tour-access.util';

export type TourVisibilityFields = Pick<
  GuidedTour,
  | 'createdBy'
  | 'developerPrivate'
  | 'assignedAdminIds'
  | 'productionManagedByAdminId'
  | 'environment'
  | 'sandboxStatus'
  | 'targetUrl'
  | 'triggerConditions'
>;

export function normalizeAssignedAdminIds(ids?: string[] | null): string[] {
  return Array.isArray(ids) ? ids.filter((id) => typeof id === 'string' && id.length > 0) : [];
}

/** Rôle métier enregistré dans contextualEngine (pas le rôle technique SDK_TOKEN). */
export function resolveContextualPublishedByRole(
  actor?: TourPermissionActor,
  creatorRole?: UserRole,
): string | undefined {
  if (!actor) {
    return undefined;
  }
  if (isSdkTokenActor(actor)) {
    if (creatorRole === UserRole.ADMIN) {
      return 'ADMIN';
    }
    if (creatorRole === UserRole.DEVELOPER) {
      return 'DEVELOPER';
    }
    // Tokens d'intégration : workflow développeur (sandbox + modération) par défaut.
    return 'DEVELOPER';
  }
  return actor.role;
}

function isLegacySdkTokenDeveloperTour(tour: TourVisibilityFields): boolean {
  const publishedRole = getContextualPublishedByRole(tour)?.toUpperCase();
  if (publishedRole !== 'SDK_TOKEN' || !tour.createdBy) {
    return false;
  }
  if (Boolean(tour.developerPrivate)) {
    return true;
  }
  if (normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0) {
    return true;
  }
  return tour.sandboxStatus === TourSandboxStatus.APPROVED;
}

export function isDeveloperOriginatedTour(tour: TourVisibilityFields): boolean {
  const publishedRole = getContextualPublishedByRole(tour)?.toUpperCase();
  if (publishedRole === 'ADMIN') {
    return false;
  }
  if (publishedRole === 'DEVELOPER') {
    return true;
  }
  if (publishedRole === 'SDK_TOKEN' && isLegacySdkTokenDeveloperTour(tour)) {
    return true;
  }
  if (isContextualAutogeneratedTour(tour)) {
    // Autogen legacy en sandbox : developer_private distingue admin (false) vs développeur (true).
    return (
      tour.environment === TourEnvironment.SANDBOX &&
      Boolean(tour.createdBy) &&
      Boolean(tour.developerPrivate)
    );
  }
  // Parcours manuel : file modération uniquement si créé avec confidentialité développeur.
  return Boolean(tour.createdBy) && Boolean(tour.developerPrivate);
}

/** Parcours admin (hors file modération développeur). */
export function isAdminOriginatedTour(tour: TourVisibilityFields): boolean {
  return Boolean(tour.createdBy) && !isDeveloperOriginatedTour(tour);
}

/** Parcours admin en sandbox : visible uniquement par le propriétaire (+ invités par grant). */
export function isAdminSandboxPrivateTour(tour: TourVisibilityFields): boolean {
  return isAdminOriginatedTour(tour) && tour.environment === TourEnvironment.SANDBOX;
}

/** Parcours admin publié en production (gestion déléguée possible). */
export function isAdminOriginatedProductionTour(tour: TourVisibilityFields): boolean {
  return tour.environment === TourEnvironment.PRODUCTION && isAdminOriginatedTour(tour);
}

/** Gestionnaire prod effectif (colonne ou créateur par défaut). */
export function resolveProductionManagerAdminId(
  tour: Pick<TourVisibilityFields, 'createdBy' | 'productionManagedByAdminId'>,
): string | null {
  if (tour.productionManagedByAdminId) {
    return tour.productionManagedByAdminId;
  }
  return tour.createdBy ?? null;
}

export function isProductionManagerAdmin(
  tour: TourVisibilityFields,
  adminId?: string,
): boolean {
  if (!adminId || !isAdminOriginatedProductionTour(tour)) {
    return false;
  }
  return resolveProductionManagerAdminId(tour) === adminId;
}

/** Sandbox approuvé via workflow dev → admin (badge « Approuvé »). */
export function isDeveloperModerationApprovedSandbox(tour: TourVisibilityFields): boolean {
  return (
    tour.environment === TourEnvironment.SANDBOX &&
    tour.sandboxStatus === TourSandboxStatus.APPROVED &&
    isDeveloperOriginatedTour(tour)
  );
}

/** Partage lecture/collab verrouillé après approbation modération développeur. */
export function isTourSharingLockedByDeveloperApproval(tour: TourVisibilityFields): boolean {
  return (
    tour.sandboxStatus === TourSandboxStatus.APPROVED && isDeveloperOriginatedTour(tour)
  );
}

export function isTourAssignedToAdmin(tour: TourVisibilityFields, adminId?: string): boolean {
  if (!adminId) {
    return false;
  }
  return normalizeAssignedAdminIds(tour.assignedAdminIds).includes(adminId);
}

/** Modérateur admin dédié (assignation unique ou dernier acteur de modération). */
export function resolveDedicatedModeratorAdminId(
  tour: Pick<TourVisibilityFields, 'assignedAdminIds'> & {
    sandboxRejectedBy?: string | null;
  },
): string | null {
  const assigned = normalizeAssignedAdminIds(tour.assignedAdminIds);
  if (assigned.length === 1) {
    return assigned[0];
  }
  return tour.sandboxRejectedBy ?? null;
}

export function isDeveloperPrivateUnassigned(tour: TourVisibilityFields): boolean {
  return Boolean(tour.developerPrivate) && normalizeAssignedAdminIds(tour.assignedAdminIds).length === 0;
}

/** Parcours sandbox ayant déjà transité par une assignation admin (cycle modération). */
export function hasDeveloperModerationSubmissionHistory(
  tour: Pick<
    GuidedTour,
    'environment' | 'assignedAdminIds' | 'assignedToAdminsAt' | 'sandboxStatus' | 'sandboxRejectedBy'
  >,
): boolean {
  if (tour.environment !== TourEnvironment.SANDBOX) {
    return false;
  }
  if (tour.assignedToAdminsAt) {
    return true;
  }
  if (normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0) {
    return true;
  }
  if (tour.sandboxRejectedBy) {
    return true;
  }
  return (
    tour.sandboxStatus === TourSandboxStatus.REJECTED ||
    tour.sandboxStatus === TourSandboxStatus.RETURNED
  );
}

/**
 * Parcours retiré de la file admin (rejet, retour ou transfert) jusqu’à réassignation développeur.
 * Le modérateur dédié reste enregistré dans assigned_admin_ids pour le prochain envoi.
 */
export function isDeveloperModerationRevokedFromAdmin(
  tour: Pick<TourVisibilityFields, 'developerPrivate' | 'sandboxStatus'>,
): boolean {
  return (
    Boolean(tour.developerPrivate) &&
    (tour.sandboxStatus === TourSandboxStatus.REJECTED ||
      tour.sandboxStatus === TourSandboxStatus.RETURNED)
  );
}

/**
 * Règle developer_private vs grant :
 * un grant view ou collaborate donné à un membre lui permet de voir le parcours
 * même si developer_private = true (la privacy ne s’applique pas aux invités explicitement partagés).
 */
export function canActorViewTour(tour: TourWithAccessGrants, actor?: TourPermissionActor): boolean {
  return canActorViewTourWithGrants(tour, actor);
}

export function assertCanViewTour(tour: TourWithAccessGrants, actor?: TourPermissionActor): void {
  assertCanViewTourWithGrants(tour, actor);
}

/** En attente modération visible pour l’admin uniquement si le parcours lui est assigné. */
export function isPendingVisibleToAdmin(tour: TourVisibilityFields, adminId?: string): boolean {
  if (tour.sandboxStatus !== TourSandboxStatus.PENDING) {
    return false;
  }
  if (!isDeveloperOriginatedTour(tour)) {
    if (isAdminSandboxPrivateTour(tour)) {
      return Boolean(adminId) && tour.createdBy === adminId;
    }
    return false;
  }
  return isTourAssignedToAdmin(tour, adminId);
}

export function assertCanModerateAssignedDeveloperTour(
  tour: TourWithAccessGrants,
  actor?: TourPermissionActor,
): void {
  if (!isAdminActor(actor)) {
    throw new ForbiddenException('Seuls les administrateurs peuvent modérer ce parcours.');
  }
  assertCanViewTour(tour, actor);
  assertCanModerateWhenNotCollaborating(tour, actor);
}

export function shouldApplyDeveloperPrivacyOnCreate(
  actor?: TourPermissionActor,
  creatorRole?: UserRole,
): boolean {
  if (isDeveloperActor(actor)) {
    return true;
  }
  if (isSdkTokenActor(actor) && creatorRole !== UserRole.ADMIN) {
    return true;
  }
  return false;
}
