export enum EventType {
  PAGE_VIEW = 'PAGE_VIEW',
  CLICK = 'CLICK',
  SCROLL = 'SCROLL',
  HOVER = 'HOVER',
  EXIT = 'EXIT',
  FORM_SUBMIT = 'FORM_SUBMIT',
  ERROR = 'ERROR',
}

export enum FrictionType {
  CLICK_MISS = 'CLICK_MISS',
  SCROLL_HESITATION = 'SCROLL_HESITATION',
  TIME_ON_PAGE_EXCESSIVE = 'TIME_ON_PAGE_EXCESSIVE',
  FORM_ABANDONMENT = 'FORM_ABANDONMENT',
  NAVIGATION_BACK = 'NAVIGATION_BACK',
}